### ISSUE TITLE
Everything seems to work but graphs are not displayed

### ISSUE THREAD

**Issue by zevarito** [ging/ackuaria#2]
Hi,

I was able to install Ackuaria with success but somethings seems to be failing silently cause graphs are not displayed on the admin panel.

Any idea what could be causing this?

**Comment by nachoaguadoc** [comment]
Hi Álvaro,

Were you able to solve the problem of not receiving the RTCP stats? All the data showed in those graphs come from RTCP.

**Comment by zevarito** [comment]
Well, I actually have enabled those in the config file and restarted
Licode, so I assume those are being sent. Can you copy/paste a log example
of Ackuaria getting stats, such things is being logged in Ackuaria's log?

2016-05-25 13:45 GMT-03:00 Ignacio Aguado notifications@github.com:

> Hi Álvaro,
> 
> Were you able to solve the problem of not receiving the RTCP stats? All
> the data showed in those graphs come from RTCP.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ging/ackuaria/issues/2#issuecomment-221631880

## 

Alvaro

**Comment by nachoaguadoc** [comment]
Hi Álvaro,

First of all you have to enable the log here: https://github.com/ging/ackuaria/blob/master/common/api.js#L388

Once you have done that, you should be able to see in the console something like this:
![captura de pantalla de 2016-05-26 09 41 19](https://cloud.githubusercontent.com/assets/6606311/15567392/6b8df22e-2326-11e6-9c24-34775877c1da.png)

**Comment by zevarito** [comment]
@nachoaguadoc yes, it log as expected if I uncomment that line, lot of stats coming in but no graphs at all.

**Comment by zevarito** [comment]
It was caused by SocketIO version conflict, there was an older version served at root level that causes de app fail silently. Here is a pull request to change the path of socketIO. #3
