### ISSUE TITLE
I can see room and agent but no streams

### ISSUE THREAD

**Issue by garcianavalon** [ging/ackuaria#5]
Hi :)

@wolmi and I are trying to set up Ackuaria in our licode infrastructure.

We installed and configured the basic example, everything working.

We installed and configured ackuaria on a different machine than the basic example. When I visit the website, I can correctly see the `basicExampleRoom` and the `Erizo Agent` but no streams are shown in either of them (failed or working, none).

Checking the logs, it succesfully connects to the MQ but we don't see any events when new streams are published.

Any idea of what can be going on?

Thanks!

**Comment by aalonsog** [comment]
Hi, 

did you ask ErizoController to send the connection events to RabbitMQ queues?

It's done in licode_config, lines 97 and 98 (https://github.com/ging/licode/blob/master/scripts/licode_default.js#L97)

BR

**Comment by wolmi** [comment]
Hi,

I've enabled all options in licode_config for reporting and it works.

Thank you

**Comment by garcianavalon** [comment]
Thanks Álvaro! :) Working great now
